---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cgvcol3mih0s/public_html/
    - /bin/cp -Rf app/* $DEPLOYPATH/app/
    - /bin/cp -Rf resources/* $DEPLOYPATH/resources/
    - /bin/cp -Rf routes/* $DEPLOYPATH/routes/
    - /bin/cp -f bootstrap/cache/*.php $DEPLOYPATH/bootstrap/cache/ || true
